/*
 * Copyright (c) 2014 Amlogic, Inc. All rights reserved.
 *
 * This source code is subject to the terms and conditions defined in the
 * file 'LICENSE' which is part of this source code package.
 *
 * Description:
 *     AMLOGIC
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dtvkit_inputsource_SurfaceOverlay */

#ifndef _Included_org_dtvkit_inputsource_SurfaceOverlay
#define _Included_org_dtvkit_inputsource_SurfaceOverlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dtvkit_inputsource_SurfaceOverlay
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL
Java_org_dtvkit_inputsource_SurfaceOverlay_nativeSetSurface
(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
